const data = {
    products: [{
            _id: "1",
            name: "computer",
            category: "computer",
            image: "/images/p3.jpg",
            price: 120,
            brand: "computer",
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: "2",
            name: "Camera",
            category: "Camera",
            image: "/images/p5.jpg",
            price: 100,
            brand: "Camera",
            countInStock: 15,
            rating: 4.0,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: "3",
            name: "headphones",
            category: "headphones",
            image: "/images/p6.jpg",
            price: 220,
            brand: "headphones",
            countInStock: 0,
            rating: 4.8,
            numReviews: 17,
            description: "high quality product",
        },
        {
            _id: "4",
            name: "headphones",
            category: "headphones",
            image: "/images/p6.jpg",
            price: 78,
            brand: "headphones",
            countInStock: 10,
            rating: 4.5,
            numReviews: 14,
            description: "high quality product",
        },
        {
            _id: "5",
            name: "Camera",
            category: "Camera",
            image: "/images/p5.jpg",
            price: 65,
            brand: "Camera",
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: "6",
            name: "computer",
            category: "computer",
            image: "/images/p3.jpg",
            price: 139,
            brand: "computer",
            countInStock: 2,
            rating: 4.5,
            numReviews: 15,
            description: "high quality product",
        },
        {
            _id: "7",
            name: "computer",
            category: "computer",
            image: "/images/p3.jpg",
            price: 120,
            brand: "computer",
            countInStock: 3,
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: "8",
            name: "Camera",
            category: "Camera",
            image: "/images/p5.jpg",
            price: 100,
            brand: "Camera",
            countInStock: 8,
            rating: 4.0,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: "9",
            name: "headphones",
            category: "headphones",
            image: "/images/p6.jpg",
            price: 220,
            brand: "headphones",
            countInStock: 2,
            rating: 4.8,
            numReviews: 17,
            description: "high quality product",
        },
        {
            _id: "10",
            name: "headphones",
            category: "headphones",
            image: "/images/p6.jpg",
            price: 78,
            brand: "headphones",
            countInStock: 10,
            rating: 4.5,
            numReviews: 14,
            description: "high quality product",
        },
        {
            _id: "11",
            name: "Camera",
            category: "Camera",
            image: "/images/p5.jpg",
            price: 65,
            brand: "Camera",
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: "12",
            name: "computer",
            category: "computer",
            image: "/images/p3.jpg",
            price: 139,
            brand: "computer",
            countInStock: 10,
            rating: 4.5,
            numReviews: 15,
            description: "high quality product",
        },
    ],
};
export default data;