export const WISHLIST_ADD_ITEM = 'WISHLIST_ADD_ITEM';
export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM';
export const PRODUCT_WISHLIST_REQUEST = "PRODUCT_WISHLIST_REQUEST";
export const PRODUCT_WISHLIST_SUCCESS = "PRODUCT_WISHLIST_SUCCESS";
export const PRODUCT_WISHLIST_FAIL = "PRODUCT_WISHLIST_FAIL";
export const PRODUCT_DETAILS_WISHLIST_REQUEST = "PRODUCT_DETAILS_WISHLIST_REQUEST";
export const PRODUCT_DETAILS_WISHLIST_SUCCESS = "PRODUCT_DETAILS_WISHLIST_SUCCESS";
export const PRODUCT_DETAILS_WISHLIST_FAIL = "PRODUCT_DETAILS_WISHLIST_FAIL";